# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mazon/io
email: support@mazon.io
description: > # Building your app one microservice at a time. 
    Whether it's text extraction, processing, manipulation or location 
    based profiles of your visitors we are assisting in construction of 
    your products.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mazon.io" # the base hostname & protocol for your site
twitter_username: mazon_io
github_username:  mazonio

# Build settings
markdown: kramdown
